default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    adapter: postgresql
    encoding: unicode
    database: ublog_development
    pool: 5
    username: postgres
    password: postgres
    host: localhost

test: &default
  primary:
    adapter: postgresql
    encoding: unicode
    database: ublog_test
    pool: 5
    username: postgres
    password: postgres

